apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: todo-app:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "8000"

          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json

            - name: tinydb
              mountPath: /tmp/tinydb

            - name: secret-token
              mountPath: /app/secrets
              readOnly: true

      volumes:
        - name: config-volume
          configMap:
            name: todo-config
            items:
              - key: todo-config.json
                path: config.json

        - name: tinydb
          persistentVolumeClaim:
            claimName: todo-pv-claim

        - name: secret-token
          secret:
            secretName: todo-secret-token
            defaultMode: 0400
            items:
              - key: token
                path: admin-token.txt
